import type { Metadata } from 'next'
import React from 'react'
import Header from '@/components/navigations/header-dashboard'
import Sidebar from '@/components/navigations/sidebar'

export const metadata: Metadata = {
  title: 'Dashboard Shopped',
  description: 'Generated by create next app',
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Header />
      <div className="flex h-screen overflow-hidden">
        <Sidebar />
        <main className="w-full pt-16">{children}</main>
      </div>
    </>
  )
}
