import type { Metadata } from 'next'

import './globals.css'

import Header from '@/components/header'
import { Footer } from '@/components/footer'

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="ligth">
      <body>
        <Header />
        <div className="flex min-h-[calc(100dvh-64px)] flex-col">
          <main className="flex-1">{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  )
}
