#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
    export PATH=${PREFIX}:${PATH}
fi

export SOURCE_FILES="api"

set -x

${PREFIX}ruff format --check --diff $SOURCE_FILES
