#!/bin/sh -e

# Use the Python executable provided from the `-p` option, or a default.
[ "$1" = "-p" ] && PYTHON=$2 || PYTHON="python3"

REQUIREMENTS="requirements.txt"
REQUIREMENTS_DEV="requirements-dev.txt"
VENV="venv"

set -x

uv pip install -r "$REQUIREMENTS"
uv pip install -r "$REQUIREMENTS_DEV"