#!/bin/sh -e

# Use the Python executable provided from the `-p` option, or a default.
[ "$1" = "-p" ] && PYTHON=$2 || PYTHON="python3"



REQUIREMENTS="requirements.txt"
REQUIREMENTS_DEV="requirements-dev.txt"
VENV="venv"

set -x

pip install uv

uv $VENV

export PREFIX=""

if [ -d '.venv' ] ; then
    export PREFIX=".venv/bin/"
    export PATH=${PREFIX}:${PATH}
fi

${PREFIX}uv pip install -r "$REQUIREMENTS"
${PREFIX}uv pip install -r "$REQUIREMENTS_DEV"