#!/bin/sh -e

export PREFIX=""

if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
    export PATH=${PREFIX}:${PATH}
fi

export SOURCE_FILES="api"

set -x

${PREFIX}uvicorn "$SOURCE_FILES.main:app" --port 8888 --reload

