import type { Metadata } from 'next'
import React from 'react'
import { Footer } from '@/components/navigations/footer-shopped'
import Header from '@/components/navigations/header-shopped'

export const metadata: Metadata = {
  title: 'Shopped Online',
  description: 'Generated by create next app',
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Header />
      <div className="flex min-h-[calc(100dvh-64px)] flex-col">
        <main className="flex-1">{children}</main>
      </div>
      <Footer />
    </>
  )
}
